"""TaskPlan and task item contracts generated by the Teacher Brain."""
from enum import Enum
from typing import List, Optional
from pydantic import Field, field_validator
from app.core.schemas.base import BaseSchema, AuditableSchema


class WorkerRole(str, Enum):
    CURRICULUM = "curriculum"
    TEACHING = "teaching"
    ASSESSMENT_DESIGN = "assessment_design"
    ASSESSMENT_EVALUATION = "assessment_evaluation"
    CODE_COACH = "code_coach"
    PROJECT_MENTOR = "project_mentor"
    ADAPTATION = "adaptation"
    SUMMARIZATION = "summarization"


class ToolGroup(str, Enum):
    LEARNER_RECORDS = "learner_records"
    KNOWLEDGE = "knowledge"
    ASSESSMENT = "assessment"
    COMPUTATION = "computation"
    ARTIFACTS = "artifacts"
    PERSISTENCE = "persistence"
    PROPOSALS = "proposals"


class TaskItem(BaseSchema):
    """A granular unit of work delegated to a specialist worker."""
    task_id: str = Field(..., description="Unique task identifier in this plan (e.g. task_1)")
    worker_role: WorkerRole = Field(..., description="Specialist worker role assigned to the task")
    objective: str = Field(..., min_length=5, description="Clear, verifiable task goal")
    dependencies: List[str] = Field(default_factory=list, description="List of task_ids that must complete before this task")
    context_references: List[str] = Field(default_factory=list, description="Passage or record IDs providing evidence")
    requested_tools: List[str] = Field(default_factory=list, description="Tool names requested by the Teacher Brain")
    output_schema: str = Field(..., description="Target Pydantic schema name expected for output")


class TaskPlan(AuditableSchema):
    """Master plan emitted by Teacher Brain (Elara) for coordinated execution."""
    plan_id: str = Field(..., description="Unique plan identifier")
    schema_version: str = Field(default="1.0.0", description="Contract schema version")
    overall_objective: str = Field(..., min_length=10, description="The high-level learning goal")
    master_instructions: str = Field(..., description="Master coordination instructions for workers")
    tasks: List[TaskItem] = Field(..., min_length=1, description="Ordered or DAG list of tasks")

    @field_validator("tasks")
    @classmethod
    def validate_unique_task_ids(cls, tasks: List[TaskItem]) -> List[TaskItem]:
        task_ids = [t.task_id for t in tasks]
        if len(task_ids) != len(set(task_ids)):
            raise ValueError("Duplicate task_id detected in TaskPlan tasks")
        return tasks
